include:
  - 'network/docker-compose-network.yaml'
  - 'kafka/docker-compose-kafka.yaml'
  - 'minio/docker-compose-minio.yaml'
  - 'mongo/docker-compose-mongo.yaml'
  - 'postgres/docker-compose-postgres.yaml'
  - 'clickhouse/clickhouse_stage/docker-compose-clickhouse-stage.yaml'
  - 'clickhouse/clickhouse_dwh/docker-compose-clickhouse-dwh.yaml'
  - 'clickhouse/clickhouse_reports/docker-compose-clickhouse-reports.yaml'