services:
  mongo:
    image: mongo:7
    container_name: mongodb
    ports: [ "27017:27017" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 15
    networks:
      - shared_network


volumes:
  mongo-data: