services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - shared_network

  mc:
    image: bitnami/minio-client:latest
    container_name: mc
    depends_on:
      - minio
    networks:
      - shared_network
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    entrypoint: /bin/sh -c "
      until mc alias set minio http://minio:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD}; do
      echo 'Waiting for MinIO...'; sleep 1;
      done;
      mc rm -r --force minio/products || true;
      mc rm -r --force minio/users || true;
      mc mb minio/products;
      mc mb minio/users;
      echo 'MinIO buckets initialized';
      exit 0
      "
    restart: on-failure

volumes:
  minio-data:


