services:
  # FastAPI
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: postgres-service
    env_file:
      - ../.env
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8001:8000"   
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
    networks:
      - shared_network

