services:
  # PostgreSQL
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U airflow -d airflow_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    # Airflow
  airflow:
      build:
        context: ./airflow
        dockerfile: Dockerfile
      container_name: airflow
      depends_on:
        postgres-db:
          condition: service_healthy
        mongodb:
          condition: service_healthy
      environment:
        - AIRFLOW__CORE__EXECUTOR=LocalExecutor
        - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
        - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-db:5432/airflow_db
      volumes:
        - ./airflow/dags:/opt/airflow/dags
      ports:
        - "8080:8080"
      command: webserver

  airflow-scheduler:
      build:
        context: ./airflow
        dockerfile: Dockerfile
      container_name: airflow-scheduler
      depends_on:
        - airflow
      volumes:
        - ./airflow/dags:/opt/airflow/dags
      command: scheduler
