
services:
  # Airflow Web Server
  airflow-webserver:
    build: ./airflow
    container_name: airflow-webserver
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:password@postgres-db/base_db
      AIRFLOW__WEBSERVER__BASE_URL: http://localhost:8080
      
      # Коннекторы для MongoDB, PostgreSQL, ClickHouse и Snowflake
      AIRFLOW_CONN_CLICKHOUSE_DEFAULT: "clickhouse://admin:secret@clickhouse/sales_db"
      AIRFLOW_CONN_POSTGRES_DEFAULT: "postgresql+psycopg2://user:password@postgres-db/base_db"
      AIRFLOW_CONN_MONGODB_DEFAULT: "mongo://admin:secret@mongodb/product_db"
      AIRFLOW_CONN_SNOWFLAKE_DEFAULT: "snowflake://fltww:585123@fltwww/base?warehouse=warehouse&role=admin"
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    depends_on:
      - postgres-db
      - clickhouse
    networks:
      - shared_network

  # Airflow Scheduler
  airflow-scheduler:
    build: ./airflow
    container_name: airflow-scheduler
    restart: always
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://user:585123@postgres-db/your_db
      
      # Коннекторы для MongoDB, PostgreSQL, ClickHouse и Snowflake
      AIRFLOW_CONN_CLICKHOUSE_DEFAULT: "clickhouse://admin:secret@clickhouse/sales_db"
      AIRFLOW_CONN_POSTGRES_DEFAULT: "postgresql+psycopg2://your_user:password@postgres-db/base"
      AIRFLOW_CONN_MONGODB_DEFAULT: "mongo://admin:secret@mongodb/product_db"
      AIRFLOW_CONN_SNOWFLAKE_DEFAULT: "snowflake://<your_username>:pass@fltww/base?warehouse=warehouse&role=admin"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
    depends_on:
      - postgres-db
      - clickhouse
    networks:
      - shared_network

networks:
  shared_network:

volumes:
  mongodb_data:
  postgres_data:
  clickhouse_data: