version: "3.9"
services:
  app:
    build: .
    container_name: product_service
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://admin:secret@mongo:27017/
      - MONGO_DB_NAME=product_db
      - PYTHONPATH=/app
    volumes:
      - ./app:/app
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    networks:
      - shared_network


