version: "3.9"
services:
  mongo:
    image: mongo:7
    container_name: mongodb
    ports: [ "27017:27017" ]
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
        - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 15


  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports: [ "8081:8081" ]
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secret
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  app:
    build: .
    container_name: fastapi-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://admin:secret@mongodb:27017/
      - MONGO_DB_NAME=product_db
      - PYTHONPATH=/app
    volumes:
      - ./app:/app 
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s


volumes:
  mongo-data:
