services:
  sales-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sales-service
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=sales
    ports:
      - "8002:8000"
    depends_on:
      kafka: 
        condition: service_healthy
    networks:
      - shared_network
